# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: West Beats by Frame Control
email: djframecontrol@gmail.com
description: "Only the best classic house, deep house, techno and tech house music for your listening pleasure."
subtitle: "Best classic house, deep house, techno and tech house music."
lang: en-us
author: Frame Control
copyright: "&#xA9; 2021"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://westbeats.com" # the base hostname & protocol for your site
twitter_username: djframecontrol

permalink: /:year/:title.html

#Timezone
timezone: Australia/Sydney

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
